<?php
// The English locale

// Before Game
$en_US["game_start"]="<bold>%nick%</bold> has started a game of Werewolf. Type \"!join\" to join. Type \"!start\" to start the game. Type \"!wait\" to increase join wait time.";
$en_US["game_wait"]="Please wait at least %answer% more seconds.";
$en_US["game_required"]="%nick%: Four or more players are required to play.";

$en_US["game_welcome"]="%answer%: Welcome to Werewolf, the popular detective/social party game (a theme of Mafia).";

// Night time
$en_US["night_first"]="It is now nighttime. All players check for PMs from me for instructions. If you did not receive one, simply sit back, relax, and wait patiently for morning.";

// Maintenance
$en_US["idle_warn"]="%nick%: <bold>You have been idling for a while. Please say something soon or you might be declared dead.</bold>";
$en_US["idle_die"]="<bold>auror</bold> didn't get out of bed for a very long time. S/He is declared dead. Appears (s)he was a <bold>seer</bold>.";

// Utilities
$en_US["help"]="(notice) Commands: <bold>help, simple, back, quit, stats, away, ping, start, retract, goat, shoot, votes, lynch, coin, wait, join, rules, admins</bold>";
$en_US["ping"]="PING! %answer%";
$en_US["coin_toss"]="<bold>%nick%<bold> tosses a coin into the air...";
$en_US["coin_land"]="The coin lands on <bold>%answer%</bold>";
$en_US["away"]="(notice) You are now marked as away.";
$en_US["back"]="(notice) You are no longer marked as away.";
$en_US["stats"]="%nick%: <bold>%answer%</bold> players: %answer2%";
$en_US["stats_none"]="%nick%: There are no players.";

// Game commands
$en_US["join"]="<bold>%nick%</bold> has joined the game.";
$en_US["quit"]="<bold>%nick%</bold> died of an unknown disease. S/He was a <bold>%answer%</bold>.";

// Notices
$en_US["game_none"]="(notice) No game is currently running.";
$en_US["ratelimit"]="(notice) This command is rate-limited. Please wait a while before using it again.";
$en_US["join_already_playing"]="(notice) You're already playing!";

// End Game
$en_US["win_villagers"]="Game over! All the wolves are dead! The villagers chop them up, BBQ them, and have a hearty meal.";
$en_US["win_wolves"]="Game over! There are the same number of wolves as villagers. The wolves eat everyone and win.";


// Directions
$en_US["wolf_part1"]="You are a <bold>wolf</bold>. It is your job to kill all the villagers. Use \"kill <nick>\" to kill a villager.";
$en_US["wolf_part2"]="Also, if you PM me, your message will be relayed to other wolves.";
$en_US["wolf_part3"]="<bold>Players:</bold> auror (wolf), ishanyx, Mithadon, MrBenC, sheep, Snuupy, Surfcash";
$en_US["wolf_kill"]="You have selected <bold>Snuupy</bold> to be killed.";
$en_US["wolf_relay"]="<bold>auror</bold> says: kill snu";

$en_US["drunk_part1"]="You have been drinking too much! You are the <bold>village drunk</bold>.";






?>